### ISSUE TITLE
ESP32 BACnet Support for controlling water valve 

### ISSUE THREAD

**Issue by harshalpt25** [chipkin/ESP32-BACnetServerExample#9]
Hi Chipkin,

As we are planning to design circuit which is having ESP32,we required to control external water valve which is supported only BACnet communication.
As we are new in BACnet communication can you please suggest any solution for ESP32 to control BACnet supported valve ?

**Comment by ssmethurst** [comment]
Hello @harshalpt25 
Please contact Chipkin directly https://store.chipkin.com/contact-us
